### ISSUE TITLE
When running `java` or `javac`, fail to load java.security file. （当运行 `java` 或 `javac` 命令时，提示无法加载 `java.security` 文件）

### ISSUE THREAD

**Issue by JackMerryYoung** [criyle/go-judger-demo#26]
Hello, I wanna develop my own OJ, and when I try to test the java compiler by sending a POST, it encounters errors when use `openjdk-21` as java compiler.
And I ensure that when using `openjdk-8` as java compiler, it won't happen. When running `sudo go-judge`, it still happens.

So I'm confused about that. Is there any way to use OpenJDK 21? 
Maybe it's a problem of environment, but when I tried to find the path of `java.security`, I got this:
`/usr/lib/jvm/java-21-openjdk-amd64/conf/security/java.security`
I added `/usr/lib/jvm/java-21-openjdk-amd64/conf/security` to the `"env"` list but nothing really does work.

Traceback when calling `javac`:
```
Exception in thread "main" java.lang.InternalError: Error loading java.security file
        at java.base/java.security.Security.initialize(Security.java:105)
        at java.base/java.security.Security.lambda$static$0(Security.java:84)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at java.base/java.security.Security.<clinit>(Security.java:83)
        at java.base/sun.security.util.SecurityProperties.getOverridableProperty(SecurityProperties.java:57)
        at java.base/sun.security.util.SecurityProperties.privilegedGetOverridable(SecurityProperties.java:48)
        at java.base/sun.security.util.SecurityProperties.includedInExceptions(SecurityProperties.java:72)
        at java.base/sun.security.util.SecurityProperties.<clinit>(SecurityProperties.java:36)
        at java.base/sun.security.util.FilePermCompat.<clinit>(FilePermCompat.java:43)
        at java.base/java.security.AccessControlContext.<init>(AccessControlContext.java:270)
        at java.base/java.security.AccessController.createWrapper(AccessController.java:649)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:461)
        at java.base/java.util.ResourceBundle$ResourceBundleProviderHelper.loadResourceBundle(ResourceBundle.java:3628)
        at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1851)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1782)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1736)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1736)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1670)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1589)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1555)
        at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:935)
        at jdk.compiler/com.sun.tools.javac.util.JavacMessages.lambda$add$0(JavacMessages.java:123)
        at jdk.compiler/com.sun.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:142)
        at jdk.compiler/com.sun.tools.javac.util.JavacMessages.setCurrentLocale(JavacMessages.java:80)
        at jdk.compiler/com.sun.tools.javac.util.JavacMessages.<init>(JavacMessages.java:114)
        at jdk.compiler/com.sun.tools.javac.util.JavacMessages.<init>(JavacMessages.java:90)
        at jdk.compiler/com.sun.tools.javac.util.JavacMessages.instance(JavacMessages.java:58)
        at jdk.compiler/com.sun.tools.javac.util.JCDiagnostic$Factory.<init>(JCDiagnostic.java:73)
        at jdk.compiler/com.sun.tools.javac.util.JCDiagnostic$Factory.instance(JCDiagnostic.java:62)
        at jdk.compiler/com.sun.tools.javac.util.Log.<init>(Log.java:323)
        at jdk.compiler/com.sun.tools.javac.util.Log.<init>(Log.java:258)
        at jdk.compiler/com.sun.tools.javac.util.Log.instance(Log.java:237)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:205)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:178)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```

My `env` looks like this now:
```
"env": [
    "PATH=/usr/bin:/bin:/usr/lib/jvm/java-21-openjdk-amd64/conf/security"
]
```

Thanks a lot if you could help me. : )

**Comment by JackMerryYoung** [comment]
@criyle

**Comment by criyle** [comment]
You may try to download the `mount.yaml` from the `go-judge` repository, put it in the same directory with the `go-judge` binary and add configuration for JDK21 similar to the configuration existed for JDK17. If you are running with docker, you need to put the configuration file into the container. After edited the configuration, restart the program and noticing if the configuration is loaded via log.

**Comment by JackMerryYoung** [comment]
Thanks a lot.
